name: inrl
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pytorch==1.13
  - torchvision==0.14
  - pandas
  - omegaconf
  - tqdm
  - opencv
  - humanfriendly
  - ca-certificates
  - certifi
  - openssl
  - matplotlib
  - jsonpickle
  - seaborn
  - ultralytics
  - Pillow
  - cudnn
